# Generated by Django 5.0.4 on 2024-04-23 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('idbook', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('author', models.CharField(max_length=200)),
                ('describe', models.TextField()),
                ('quantity', models.IntegerField()),
            ],
        ),
    ]
