# Generated by Django 5.0.4 on 2024-04-24 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ReturnBook',
            fields=[
                ('idreturn', models.AutoField(primary_key=True, serialize=False)),
                ('idborrow', models.IntegerField()),
                ('idbook', models.IntegerField()),
                ('name_cust', models.CharField(max_length=200)),
                ('cccd_cust', models.CharField(max_length=12)),
                ('sdt', models.CharField(max_length=15)),
                ('address_cust', models.TextField()),
                ('quantity', models.IntegerField()),
                ('address_lib', models.TextField()),
                ('date_borrow', models.DateField()),
                ('date_return_expected', models.DateField()),
                ('status', models.TextField()),
                ('date_return', models.DateField()),
                ('total_money', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
    ]
