# Generated by Django 5.0.4 on 2024-04-23 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BorrowBook',
            fields=[
                ('idborrow', models.AutoField(primary_key=True, serialize=False)),
                ('idbook', models.IntegerField()),
                ('name_cust', models.CharField(max_length=200)),
                ('cccd_cust', models.CharField(max_length=12)),
                ('sdt', models.CharField(max_length=15)),
                ('address_cust', models.TextField()),
                ('quantity', models.IntegerField()),
                ('address_lib', models.TextField()),
                ('date_borrow', models.DateField()),
                ('date_return_expected', models.DateField()),
                ('status', models.TextField()),
            ],
        ),
    ]
